export const queryConstants = {
  GET_IIKO_TERMINAL_SECTION_BY_ID: "GET_IIKO_TERMINAL_SECTION_BY_ID",
  GET_IIKO_ORDER_TYPES: "GET_IIKO_ORDER_TYPES",
  GET_NON_MODIFIER_LIST: "GET_NON_MODIFIER_LIST",
  GET_CRM_CREDENTIALS: "GET_CRM_CREDENTIALS",
  GET_COURIER_FARE_LIST: "GET_COURIER_FARE_LIST",
  GET_COURIER_TYPE_LIST: "GET_COURIER_TYPE_LIST",
  GET_CUSTOMERS_LIST: "GET_CUSTOMERS_LIST",
  GET_BRANCH_ORDERS_AND_ROUTES: "GET_BRANCH_ORDERS_AND_ROUTES",
  GET_MENU_PRODUCT_LIST: "GET_MENU_PRODUCT_LIST",
  GET_COURIER_LIST_BY_BRANCH: "GET_COURIER_LIST_BY_BRANCH",
  GET_SALES_PIPELINE: "GET_SALES_PIPELINE",
  GET_NEAREST_BRANCH: "GET_NEAREST_BRANCH",
  GET_COURIERS_BY_BRANCH: "GET_COURIERS_BY_BRANCH",
  GET_ORDERS_LIST_BRANCH_SCREEN: "GET_ORDERS_LIST_BRANCH_SCREEN",
  GET_ORDERS_LIST_PRODUCTS_COUNT: "GET_ORDERS_LIST_PRODUCTS_COUNT",
  GET_SMS_HISTORY: "GET_SMS_HISTORY",
  GET_PAYMENT_CREDENTIAL_LIST: "GET_PAYMENT_CREDENTIAL_LIST",
  GET_PAYME_LIST: "GET_PAYME_LIST",
  GET_TRACKING_LIST: "GET_TRACKING_LIST",
  GET_COURIER_LIST: "GET_COURIER_LIST",
  GET_API_KEYS_ID_LIST: "GET_API_KEYS_ID_LIST",
  GET_CUSTOMERS_BY_PHONE: "GET_CUSTOMERS_BY_PHONE",
  GET_COURIER_BY_ID: "GET_COURIER_BY_ID",
  GET_BANNERS_LIST: "GET_BANNERS_LIST",
  GET_BANNER_BY_ID: "GET_BANNER_BY_ID",
  GET_BRANCH_USERS_LIST: "GET_BRANCH_USERS_LIST",
  GET_CUSTOM_TEMPLATE_LIST: "GET_CUSTOM_TEMPLATE_LIST",
  GET_CUSTOM_TEMPLATE_BY_ID: "GET_CUSTOM_TEMPLATE_BY_ID",
  GET_RFM_CUSTOMERS_LIST: "GET_RFM_CUSTOMERS_LIST",
  GET_RFM: "GET_RFM",
  GET_ROUTES_LIST: "GET_ROUTES_LIST",
  GET_GPT_REPORT: "GET_GPT_REPORT",
  GET_BRANCH_USER_BY_ID: "GET_BRANCH_USER_BY_ID",
  GET_GENERAL_PROMOCODE_REPORT_LIST: "GET_GENERAL_PROMOCODE_REPORT_LIST",
  GET_PROMOCODE_REPORT_LIST: "GET_PROMOCODE_REPORT_LIST",
  GET_PROMOCODE_BY_CLIENT_REPORT_LIST: "GET_PROMOCODE_BY_CLIENT_REPORT_LIST",
  GET_CRM_CUSTOMER_INFO: "GET_CRM_CUSTOMER_INFO",
  GET_GROUP_BY_ID: "GET_GROUP_BY_ID",
  GET_KDS_ORDER_LIST: "GET_KDS_ORDER_LIST",
  GET_BUFFER_LIST: "GET_BUFFER_LIST",
  GET_PRODUCT_PREDICTION_LIST_KITCHEN: "GET_PRODUCT_PREDICTION_LIST_KITCHEN",
  GET_HOUR_PREDICTION_LIST_KITCHEN: "GET_HOUR_PREDICTION_LIST_KITCHEN",
  GET_PRODUCT_PREDICTION_LIST: "GET_PRODUCT_PREDICTION_LIST",
  GET_ORDER_REPORT_WITH_TIME: "GET_ORDER_REPORT_WITH_TIME",
  //aggregators
  GET_AGGREGATORS: "GET_AGGREGATORS",

  //customers
  GET_CUSTOMER_BY_ID: "GET_CUSTOMER_BY_ID",
  GET_COURIER_FINANCE_REPORT: "GET_COURIER_FINANCE_REPORT",
  GET_ORDER_FINANCE_REPORT: "GET_ORDER_FINANCE_REPORT",

  // ORDERS
  GET_ORDER_LIST: "GET_ORDER_LIST",
  GET_ORDER_BY_ID: "GET_ORDER_BY_ID",
  GET_DEFAULT_PRODUCTS_TO_ORDER: "GET_DEFAULT_PRODUCTS_TO_ORDER",
  GET_COMPUTE_DELIVERY_PRICE: "GET_COMPUTE_DELIVERY_PRICE",

  //NOTIFICATIONS_ALERTS
  GET_NOTIFICATION_ALERTS: "GET_NOTIFICATION_ALERTS",
  GET_NOTIFICATION_ALERT_BY_ID: "GET_NOTIFICATION_ALERT_BY_ID",
  GET_NOTIFICATION_HISTORY: "GET_NOTIFICATION_HISTORY",

  //BALANCE
  GET_BALANCE: "GET_BALANCE",
  GET_TRANSACTION: "GET_TRANSACTION",

  //GEOZONE
  GET_GEOZONE: "GET_GEOZONE",
  GET_GEOZONEBYID: "GET_GEOZONEBYID",
  GET_FREE_GEOZONE: "GET_FREE_GEOZONE",
  GET_FREE_GEOZONEBYID: "GET_FREE_GEOZONEBYID",

  //FARES
  GET_FARE_BY_ID: "GET_FARE_BY_ID",
  GET_FARES: "GET_FARES",

  GET_BRANCH_LIST: "GET_BRANCH_LIST",
  GET_BRANCH_BY_ID: "GET_BRANCH_BY_ID",
  GET_NON_ORIGIN_MODIFIER_LIST: "GET_NON_ORIGIN_MODIFIER_LIST",
  GET_PERMISSION_LIST: "GET_PERMISSION_LIST",
  GET_USER_ROLE_PERMISSION_LIST: "GET_USER_ROLE_PERMISSION_LIST",
  GET_USER_ROLE_LIST: "GET_USER_ROLE_LIST",

  //SHIPPER-USERS
  GET_SHIPPER_USERS: "GET_SHIPPER_USERS",

  //COURIER_ATTENDANCE
  GET_COURIER_ATTENDANCE: "GET_COURIER_ATTENDANCE",

  //GET_TRANSACTION_REPORT
  GET_TRANSACTION_REPORT: "GET_TRANSACTION_REPORT",

  //PRODUCTS
  GET_FAVOURITED_PRODUCTS: "GET_FAVOURITED_PRODUCTS",
  GET_PRODUCT_BY_ID: "GET_PRODUCT_BY_ID",
  GET_COMBO_BY_ID: "GET_COMBO_BY_ID",
  GET_MENU_LIST: "GET_MENU_LIST",
  GET_MENU_BY_ID: "GET_MENU_BY_ID",

  //AGGREGATORS
  GET_CRM_AGGREGATORS: "GET_CRM_AGGREGATORS",
  GET_CRM_AGGREGATOR: "GET_CRM_AGGREGATOR",

  //BONUS/PENALTY
  GET_COURIER_BPS: "GET_COURIER_BP",
  GET_COURIER_BP: "GET_COURIER_BP",

  // CATEGORY
  GET_CATEGORY_WITH_PRODUCTS: "GET_CATEGORY_WITH_PRODUCTS",
  GET_CHILD_CATEGORIES: "GET_CHILD_CATEGORIES",
  GET_MODIFIERS_LIST: "GET_MODIFIERS_LIST",

  //SOURCE SETTINGS
  GET_SOURCE_SETTINGS: "GET_SOURCE_SETTINGS",

  //GET_SMS_TEMPLATE
  GET_SMS_TEMPLATE: "GET_SMS_TEMPLATE",

  // Marketing
  GET_NEWS_LIST: "GET_NEWS_LIST",
  GET_NEWS_BY_ID: "GET_NEWS_BY_ID",
  GET_VACANCY_LIST: "GET_VACANCY_LIST",
  GET_VACANCY_BY_ID: "GET_VACANCY_BY_ID",
  GET_VACANCY_CANDIDATE_LIST: "GET_VACANCY_CANDIDATE_LIST",

  //REPORTS
  GET_EXTERNAL_DELIVERY_REPORT: "GET_EXTERNAL_DELIVERY_REPORT",

  GET_CUSTOMER_BIRTHDAYS: "GET_CUSTOMER_BIRTHDAYS",
  GET_GROUP_LIST: "GET_GROUP_LIST",
};

export const defaultProps = {
  enabled: false,
};
